fix: add optional `utm_data` param to createUser on useSignUpForm
BetterTheWorld/react-native-rewards pull request #32
Opened 2024-08-16 13:40 UTC by borismobile

I confirmed with Abhi yesterday that `utm_data` should be sent along with the signup, not as a url param on the webview.

This MR adds an optional form field that will be populated with the concatenated "clubs" value to satisfy the UTM parameter requirement on sports-connect

```bash
curl --location 'https://staging.authrewards.com/users?utm_data=%22utm_medium%3Dmobile&test=hardcoded%22' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'X-REWARDS-PARTNER-ID: A2DE537C' \
--data-raw '{
    "user": {
        "email": "averma+34@flipgive.com",
        "password": "password1@P",
        "full_name": "1234 5678",
        "country": "USA",
        "postal_code": "12345",
        "city": "abcd",
        "state": "null",
        "utm_data": {
            "abcd": "en",
            "efgh": "abdceahfkjl"
        }
    }
}
'
```

2024-08-16 13:42 UTC, borismobile commented
I tested this yesterday with Abhi using a hardcoded value on the submit function and indeed it was getting populated in the database:

```

  const handleSubmit = () => {
    // Reset errors
    setErrors({ fullName: '', email: '', password: '' });

  ...

    if (isValid) {
      onSubmit({
        fullName,
        email,
        password,
        utmData: { content: 'bestclub2' },
      });
    }
  };
  
  
![image](https://github.com/user-attachments/assets/5c3d1be7-7686-400a-8365-8f5e47cc19e6)

2024-08-16 13:45 UTC, ddiazFG commented
Let's discuss this with Nick, I remember talking to him and the requirement is different, I may have changed. can you confirm by slack, where to have more visiviliadd?

2024-08-16 13:59 UTC, ddiazFG commented
Also, please put it in draft until finished

2024-08-16 13:59 UTC, ddiazFG requested changes
Draft

2024-08-19 14:36 UTC, ddiazFG commented
Created: https://github.com/BetterTheWorld/react-native-rewards/pull/33

2024-08-19 14:53 UTC, closed without merging